init

diff --git a/backup_optimized b/backup_optimized
--- a/backup_optimized
+++ b/backup_optimized
@@ -47,7 +47,7 @@ function prereq_check()
 
 function command_exec_dir_check()
 {
-	if [ ! -f backup ]; then
+	if [ ! -f backup_optimized ]; then
 		echo "error: command should be executed from backupNrestore directory"
 		exit 1
 	fi
@@ -465,11 +465,25 @@ function SNAPSHOT_WEBSITE()
     fi
 }
 
+function is_tool_initialized()
+{
+    if [ ! -f ../.backupNrestore.init ]; then
+        echo "  error: backupNrestore should be initialized before using it"
+        echo
+        echo "  Help: Execute the following command"
+        echo
+        echo "      ./init "
+        echo
+        exit 1
+    fi
+}
+
 function main()
 {
     get_current_dir
     prereq_check
     command_exec_dir_check
+    is_tool_initialized
     get_tool_name
     get_timestamp
     import_config
@@ -504,6 +518,7 @@ function main()
 
 # Main Code
 ./banner.sh 2> /dev/null
+
 main
 
 
diff --git a/init b/init
--- a/init
+++ b/init
@@ -1,4 +1,37 @@
-cd ..
+#!/bin/bash
+# Version 1.4
+#
+#		Author	: Viki (a) Vignesh Natarajan 
+#		Contact	: vikiworks.io
+#		Licence : MIT
+
+
+function get_current_dir()
+{
+    CURRENT_DIR=`pwd -P`
+}
+
+function command_exec_dir_check()
+{
+	if [ ! -f init ]; then
+		echo "error: command should be executed from backupNrestore directory"
+		exit 1
+	fi
+}
+
+function import_config()
+{
+    cd $CURRENT_DIR
+    source ./config.sh
+    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ] "; exit 1; }
+    echo
+    echo
+}
+
+get_current_dir
+command_exec_dir_check
+import_config
+
 echo 
 echo "  Going to delete .git folder if exist"
 echo 
@@ -9,10 +42,13 @@ if [ "$USER_INPUT" == "YES" ]; then
     echo
     echo "  Deleting all .git folders"
     echo
+    cd $WEBSITE_ROOT_DIR
+    [ $? -ne 0 ] && { echo "[ ERROR ] [ ${LINENO} ] "; exit 1; }
     find . -name .git -delete
     echo
     echo "  INIT SUCCESSFUL"
     echo
+    touch .backupNrestore.init
 else
     echo
     echo "  no files are deleted"
