command execution directory validation

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -13,6 +13,14 @@ function get_current_dir()
     CURRENT_DIR=`pwd -P`
 }
 
+function command_exec_dir_check()
+{
+	if [ ! -f backup ]; then
+		echo "error: command should be executed from backupNrestore directory"
+		exit 1
+	fi
+}
+
 function get_tool_name()
 {
     basename $CURRENT_DIR 2> /dev/null 1> /dev/null 
@@ -419,6 +427,7 @@ function SNAPSHOT_WEBSITE()
 function main()
 {
     get_current_dir
+    command_exec_dir_check
     get_tool_name
     get_timestamp
     import_config
diff --git a/db_backup b/db_backup
--- a/db_backup
+++ b/db_backup
@@ -11,6 +11,14 @@ function get_current_dir()
     CURRENT_DIR=`pwd -P`
 }
 
+function command_exec_dir_check()
+{
+	if [ ! -f db_backup ]; then
+		echo "error: command should be executed from backupNrestore directory"
+		exit 1
+	fi
+}
+
 function get_tool_name()
 {
     basename $CURRENT_DIR 2> /dev/null 1> /dev/null 
@@ -280,6 +288,7 @@ function export_website_database()
 function main()
 {
     get_current_dir
+    command_exec_dir_check
     get_tool_name
     import_config
     backup_config
diff --git a/db_truncate b/db_truncate
--- a/db_truncate
+++ b/db_truncate
@@ -17,6 +17,14 @@ ARG_COUNT=$#
 TABLE_LIST=""
 flag=0
 
+function command_exec_dir_check()
+{
+	if [ ! -f db_truncate ]; then
+		echo "error: command should be executed from backupNrestore directory"
+		exit 1
+	fi
+}
+
 function init_commands(){
     C_GREP=$(which grep)
     [ $? -ne 0 ] && { echo "  [ ERROR ] [ ${LINENO} ] Command doesn't exist ( grep ) "; exit 1; }
@@ -72,7 +80,9 @@ function retry_delete_tables(){
 
 
 echo
+
 check_arguments
+command_exec_dir_check
 init_commands
 
 retry_delete_tables
diff --git a/restore b/restore
--- a/restore
+++ b/restore
@@ -15,6 +15,14 @@ function get_current_dir()
     CURRENT_DIR=`pwd -P`
 }
 
+function command_exec_dir_check()
+{
+	if [ ! -f restore ]; then
+		echo "error: command should be executed from backupNrestore directory"
+		exit 1
+	fi
+}
+
 function create_db_if_not_exist(){
     DB_NAME=$1
     echo "Creating DB if not exist ( $DB_NAME )"
@@ -473,6 +481,7 @@ function configure_ownership(){
 function main()
 {
     get_current_dir
+    command_exec_dir_check
     import_config
     set_source_path
     check_whether_webroot_dir_inside_source_dir
diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -14,6 +14,14 @@ function get_current_dir()
     CURRENT_DIR=`pwd -P`
 }
 
+function command_exec_dir_check()
+{
+	if [ ! -f snapshot ]; then
+		echo "error: command should be executed from backupNrestore directory"
+		exit 1
+	fi
+}
+
 function import_config()
 {
     cd $CURRENT_DIR
@@ -72,6 +80,12 @@ function git_checkout()
     switch2master_branch_if_exist
 }
 
+function remove_git_from_backupNrestore_dir()
+{
+    cd $CURRENT_DIR
+    rm -rf .git
+}
+
 function git_commit()
 {
     cd ../
@@ -119,6 +133,7 @@ function git_snapshot()
 {
     is_git_installed
     get_current_dir
+    command_exec_dir_check
 
     if [ $ARG1 == "no_db_export"]; then
         echo "  [ status ] snapshot without db export"
@@ -130,6 +145,7 @@ function git_snapshot()
     import_config
     is_git_config_valid
     get_timestamp
+    remove_git_from_backupNrestore_dir
     git_commit
 }
 
