backup optimized and snapshot, changed traditional backup without snapshot

diff --git a/backup_optimized b/backup_optimized
--- a/backup_optimized
+++ b/backup_optimized
@@ -34,10 +34,15 @@ function prereq_check()
 {
     which rsync 2>/dev/null 1>/dev/null
     if [ $? -ne 0 ]; then
-        echo "  error: this utility needs rsync, rsync not installed"
+        echo "  error: this utility needs rsync | rsync not installed"
         exit 1
     fi
 
+    which git 2>/dev/null 1>/dev/null
+    if [ $? -ne 0 ]; then
+        echo "  error: this utility needs git | git not installed"
+        exit 1
+    fi
 }
 
 function command_exec_dir_check()
