snapshot and backup

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -6,6 +6,8 @@
 #		Contact	: vikiworks.io
 #		Licence : MIT
 
+db_exported=0
+
 function get_current_dir()
 {
     CURRENT_DIR=`pwd -P`
@@ -403,10 +405,15 @@ function generate_backup()
     echo
 }
 
-function GIT_SNAPSHOT()
+function SNAPSHOT_WEBSITE()
 {
     cd $CURRENT_DIR
-    ./git_snapshot 2> /dev/null 1> /dev/null
+
+    ./snapshot "no_db_export" 2> /dev/null 1> /dev/null
+
+    if [ $? -eq 0 ]; then
+        echo " warning: snapshot failed, proceeding backup without snapshot"
+    fi
 }
 
 function main()
@@ -431,7 +438,7 @@ function main()
     create_backup_dir_with_timestamp
     print_config
     export_website_database
-    GIT_SNAPSHOT
+    SNAPSHOT_WEBSITE
     export_website_data
     clear_log_files
     remove_unused_files_n_folders_from_backup
diff --git a/snapshot b/snapshot
--- a/snapshot
+++ b/snapshot
@@ -6,6 +6,9 @@
 #		Contact	: vikiworks.io
 #		Licence : MIT
 
+ARG0=$0
+ARG1=$1
+
 function get_current_dir()
 {
     CURRENT_DIR=`pwd -P`
@@ -20,7 +23,7 @@ function import_config()
     echo
 }
 
-function empty_config_check()
+function is_git_config_valid()
 {
     config_error=0
 
@@ -46,10 +49,6 @@ function get_timestamp()
     HOUR=$(date '+%H')
     MINUTE=$(date '+%M')
     TIME_STAMP="D${DAY}${MONTH}${YEAR}#T${HOUR}${MINUTE}"
-}
-
-function backup_db(){
-    ./db_backup
 }
 
 function switch2master_branch_if_exist()
@@ -99,11 +98,44 @@ function git_commit()
     cd $CURRENT_DIR
 }
 
-get_current_dir
-backup_db
-import_config
-empty_config_check
-get_timestamp
-git_commit
+function is_git_installed()
+{
+    which git 2>/dev/null 1>/dev/null
+    if [ $? -ne 0 ]; then 
+        echo "notice: git is not installed, unable to snapshot"
+        echo ""
+        echo "Install git before trying snapshot"
+        echo ""
+        exit 1
+    fi
+}
 
+function backup_db(){
+    echo "  exporting database(s)"
+    ./db_backup
+}
 
+function git_snapshot()
+{
+    is_git_installed
+    get_current_dir
+
+    if [ $ARG1 == "no_db_export"]; then
+        echo "  [ status ] snapshot without db export"
+    else
+        echo "  [ status ] snapshot with db export"
+        backup_db
+    fi
+    
+    import_config
+    is_git_config_valid
+    get_timestamp
+    git_commit
+}
+
+if [ -z $ARG1 ]; then
+    ARG1="export_db"
+fi
+
+git_snapshot 
+exit 0
